#!/bin/sh

if [ -z "${1}" ]
then
  echo "Project name can not be null"
  exit 1
fi

PROJECT_NAME=$( echo "$1" | tr '[:lower:]' '[:upper:]' )

PROJECT_VERSION_MAJOR=$2
case "${PROJECT_VERSION_MAJOR}" in
  ''|*[!0-9]*) echo "PROJECT_VERSION_MAJOR is not a number"; exit 1;;
esac

PROJECT_VERSION_MINOR=$3
case "${PROJECT_VERSION_MINOR}" in
  ''|*[!0-9]*) echo "PROJECT_VERSION_MINOR is not a number"; exit 1;;
esac

PROJECT_VERSION_PATCH=$4
case "${PROJECT_VERSION_PATCH}" in
  ''|*[!0-9]*) echo "PROJECT_VERSION_PATCH is not a number"; exit 1;;
esac

PROJECT_VERSION_RELEASE_CANDIDATE=$5
case "${PROJECT_VERSION_RELEASE_CANDIDATE}" in
  ''|*[!0-9]*) echo "PROJECT_VERSION_RELEASE_CANDIDATE is not a number"; exit 1;;
esac


echo \
"VERSION_MAJOR ?= ${PROJECT_VERSION_MAJOR}
VERSION_MINOR ?= ${PROJECT_VERSION_MINOR}
VERSION_PATCH ?= ${PROJECT_VERSION_PATCH}
VERSION_RELEASE_CANDIDATE ?= ${PROJECT_VERSION_RELEASE_CANDIDATE}
" > makefile.am

echo \
"#ifndef ${PROJECT_NAME}_VERSION_H
#define ${PROJECT_NAME}_VERSION_H

#define ${PROJECT_NAME}_VERSION_MAJOR ${PROJECT_VERSION_MAJOR}
#define ${PROJECT_NAME}_VERSION_MINOR ${PROJECT_VERSION_MINOR}
#define ${PROJECT_NAME}_VERSION_PATCH ${PROJECT_VERSION_PATCH}
#define ${PROJECT_NAME}_VERSION_RELEASE_CANDIDATE ${PROJECT_VERSION_RELEASE_CANDIDATE}

#define ${PROJECT_NAME}_VERSION_VARIABLE_VALUE_TO_STRING_HELPER(variable) #variable
#define ${PROJECT_NAME}_VERSION_VARIABLE_VALUE_TO_STRING(variable) ${PROJECT_NAME}_VERSION_VARIABLE_VALUE_TO_STRING_HELPER(variable)

#define ${PROJECT_NAME}_VERSION_RELEASE_CANDIDATE_STATUS \\
        ${PROJECT_NAME}_VERSION_RELEASE_CANDIDATE > 0 ? 1 : 0

#if ${PROJECT_NAME}_VERSION_RELEASE_CANDIDATE_STATUS
    #define ${PROJECT_NAME}_VERSION_TEXT_FORMAT(version_major, version_minor, version_patch, version_release_candidate) \\
        ${PROJECT_NAME}_VERSION_VARIABLE_VALUE_TO_STRING(version_major) \".\" ${PROJECT_NAME}_VERSION_VARIABLE_VALUE_TO_STRING(version_minor) \".\" ${PROJECT_NAME}_VERSION_VARIABLE_VALUE_TO_STRING(version_patch) \"-rc\" ${PROJECT_NAME}_VERSION_VARIABLE_VALUE_TO_STRING(version_release_candidate)
#else
    #define ${PROJECT_NAME}_VERSION_TEXT_FORMAT(version_major, version_minor, version_patch) \
        ${PROJECT_NAME}_VERSION_VARIABLE_VALUE_TO_STRING(version_major) \".\" ${PROJECT_NAME}_VERSION_VARIABLE_VALUE_TO_STRING(version_minor) \".\" ${PROJECT_NAME}_VERSION_VARIABLE_VALUE_TO_STRING(version_patch)
#endif

#if ${PROJECT_NAME}_VERSION_RELEASE_CANDIDATE_STATUS
    #define ${PROJECT_NAME}_VERSION_TEXT \\
        ${PROJECT_NAME}_VERSION_TEXT_FORMAT(${PROJECT_NAME}_VERSION_MAJOR, ${PROJECT_NAME}_VERSION_MINOR, ${PROJECT_NAME}_VERSION_PATCH, ${PROJECT_NAME}_VERSION_RELEASE_CANDIDATE)
#else
    #define ${PROJECT_NAME}_VERSION_TEXT \\
        ${PROJECT_NAME}_VERSION_TEXT_FORMAT(${PROJECT_NAME}_VERSION_MAJOR, ${PROJECT_NAME}_VERSION_MINOR, ${PROJECT_NAME}_VERSION_PATCH)
#endif

#endif //${PROJECT_NAME}_VERSION_H
" > version.h
